# Generated by Django 5.2.7 on 2025-10-30 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='coin_reward',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='level',
            name='required_topics',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='level',
            name='xp_reward',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.CreateModel(
            name='UserLevelCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_levels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'level')},
            },
        ),
    ]
