# Generated by Django 5.2.7 on 2025-10-30 06:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_level_coin_reward_level_required_topics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='explanation',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Explanation'),
        ),
    ]
