# Generated by Django 5.2.7 on 2025-10-31 07:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_alter_topic_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingproblem',
            name='description',
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='explanation',
            field=django_ckeditor_5.fields.CKEditor5Field(default=' ', verbose_name='Explanation'),
        ),
    ]
